spring:
  application:
    name: fon-nastava

  # podesavanja baze
  datasource:
    url: jdbc:postgresql://localhost:5434/fon_nastava
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false # ne dozvoli da hibernate sesija bude dostupna tokom celog izvrsavanja zahteva

  # Jackson configuration
  jackson:
    # Date/Time serialization
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: false
    deserialization:
      read-date-timestamps-as-nanoseconds: false
    # Null handling
    default-property-inclusion: non_null
    # Time zone
    time-zone: CET
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ

# Server configuration
server:
  port: 1389

# Logging configuration
logging:
  level:
    root: INFO
    rs.ac.bg.fon: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
